reporting:
  dir: ./coverage/server
  reports:
    - json
    - html
    - cobertura
    - text-summary
  report-config:
    text-summary: { file: text_summary.txt }
instrumentation:
  include-all-sources: true
  default-excludes: true
  excludes: [
    'src/client/**',
    '__tests__/**',
    'coverage*/**',
    'reports/**',
    'dist/**',
    'dev/**',
    'config/**',
    'gulpfile.js',
    'webpack.config.js',
    'jest.config.js',
  ]
