options:
  formatter:              stylish
  max-warnings:           0
  merge-default-rules:    true
files:
  include:                'src/client/scss/**/*.s+(a|c)ss'
rules:
  no-ids:                   0
  no-qualifying-elements:   0
  no-vendor-prefixes:       0
  class-name-format:        0
  variable-name-format:     0
  clean-import-paths:       0
  nesting-depth:            0
  property-sort-order:      0
  force-attribute-nesting:  0
  force-element-nesting:    0
  force-pseudo-nesting:     0
  leading-zero:             0
